### ISSUE TITLE
Create a crossbar docker image

### ISSUE THREAD

**Issue by sametmax** [crossbario/crossbarwww#17]
Many people are not from the Python world. I can be scary to see something is using another technology and prevent your from using it.

Making a clean, preconfigured docker image would help. To try it out, people don't need to put their hand on the JSON config file : start the image, then just write a client, connect, and run.

Maybe later, we may think about creating a packages for Linux such as deb or rpm as well.

**Comment by tomByrer** [comment]
> with comments and a documentation

+1

**Comment by goeddea** [comment]
This now exists (though we could, of course, have more documentation).
