### ISSUE TITLE
Server in Node?

### ISSUE THREAD

**Issue by tomByrer** [crossbario/crossbarwww#23]
I'm a bit confused if Node can be used as a server.  Website only tags the Python server as a server, but [this line](http://www.smashingmagazine.com/2015/01/13/why-ajax-isnt-enough/) alludes otherwise:

> JavaScript implementation (Autobahn|JS) that runs both in the browser and in Node.js, allowing you to do pure JavaScript-only applications

Not too interested in learning Python just for 1 project.  Meteor seems to fit the Sockets sync issue in full JS stack.

**Comment by oberstet** [comment]
You can do full-stack JS development with AutobahnJS: write your frontend and backend components both in JS. The implementation language of Crossbar.io itself does not matter for app developers - look at Crossbar.io like a blackbox (similar to RabbitMQ for example).
