### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Vayel** [crossbario/crossbarwww#25]
In the [QuickStart page](http://crossbar.io/docs/Quick-Start/), at the end of the section *Create an Application*, the link *overview* leads to an unexisting page. Its host reference should be `http://crossbar.io/docs/Choose-your-Weapon/` instead of `http://crossbar.io/docs/Choose-your-weapon/`.

**Comment by goeddea** [comment]
Thanks for the catch! Is fixed now.
