### ISSUE TITLE
The documentation page should be the TOC

### ISSUE THREAD

**Issue by Vayel** [crossbario/crossbarwww#28]
To be clearer, that [page](http://crossbar.io/docs/) should be that [one](http://crossbar.io/docs/TOC/).

**Comment by oberstet** [comment]
It once was. Lots of discussions later, we thought it would be nice to have the docs landing page not be a plain TOC. You think differently?

**Comment by Vayel** [comment]
To me, it makes it far more difficult for beginners to know where they should start. At least, that's what I feel when I'm on the documentation landing page. Today, it's not direct enough, there is too much text, repeating the website landing page. I think the docs are not here to explain what Crossbar.io is (the website landing page does the job) but how to use it.

**Comment by oberstet** [comment]
I see. It's true that the docs landing page is repeating stuff from the Web site landing page.

The problem with the TOC is: it doesn't give guidelines also. Do you have examples of other projects with great docs?

E.g. looking at https://docs.djangoproject.com/, their landing page is indeed a mix of TOC with minimal text ...

**Comment by Vayel** [comment]
The Django docs landing page appears to be perfect. With a little text under the titles of the TOC, Crossbar's one would be too. Then, the TOC (*i.e.* the landing page) would be:

___
# Documentation

Welcome to the Crossbar.io documentation. See the homepage if you did not.

## How it works

Learn the underlying concepts of Crossbar.io.

### Introduction

Some text.

### Contributing

Notes for developers working on the Crossbar.io code base (not application developers).

### Licenses

Some text.

## How to use it

### Getting started

Some text.

#### Installation

Some text.

#### Quick Start

Some text.

### Programming

Some text. See #29.

### Administration

Some text.

#### Configuration

Some text.

#### Going to Production

Some text.

#### Compliance and Performance

Some text.
___

**Comment by oberstet** [comment]
@Vayel that makes a lot of sense and is a good start. We'll rework the docs main page for above

**Comment by Vayel** [comment]
I made a copy of the wiki [here](https://github.com/Vayel/crossbardocs/wiki) if you want.

**Comment by goeddea** [comment]
Thanks the for the substantial contributions. Will implement this over the next few days.

**Comment by Vayel** [comment]
Thanks for your reactions. Some parts should probably be updated:

* [Introduction](https://github.com/Vayel/crossbardocs/wiki#introduction), not to repeat the homepage (see #26)
* [Programming](https://github.com/Vayel/crossbardocs/wiki#programming), not to repeat `autobahnX.ws`

**Comment by goeddea** [comment]
... and more good input :)

**Comment by Vayel** [comment]
Concerning the Programming section, don't forget #24. Clearly explain that components can be launched without Crossbar.io (see `autobahnX.ws` for more details) before teaching how to start them with the `config.json` file.

**Comment by goeddea** [comment]
- Documentation landing page is a TOC with minimal comments again.
- Updated Introduction page. I don't think that this can't repeat information from the homepage. We cannot assume a set reading order, so some information will need to be replicated in order for people not to be lost.
