### ISSUE TITLE
non-ASCII characters in wiki not possible

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbarwww#32]
markupsafe does not handle non-7bit-ASCII characters

While these can be avoided in wiki pages, the problem can also come up with the cleartext names of GitHub users, since these are also processed. A last commit by me with my cleartext name set as "Gödde" produced an error, while "Goedde" processed without a hitch.

**Comment by oberstet** [comment]
One should not use non US-ASCII7 chars. Nowhere. And particular not in Git config `username` ..
