### ISSUE TITLE
The message of a commit is displayed

### ISSUE THREAD

**Issue by Vayel** [crossbario/crossbarwww#37]
The end of that [page](http://crossbar.io/docs/) contains the message of a commit. Is it expected?

**Comment by goeddea** [comment]
I see no problem with this - but it's not nice that the message is truncated, so this should be changed to either not show the message or show it fully.

**Comment by Vayel** [comment]
Isn't it too technical? It appears like an uncaught exception.

**Comment by goeddea** [comment]
Commit messages are no longer displayed in the docs. Closing.
