### ISSUE TITLE
Docs landing page: describe links

### ISSUE THREAD

**Issue by Vayel** [crossbario/crossbarwww#40]
The documentation landing page is really clear now. But maybe it could be more if you added a short sentence to describe each/some link(s). For instance:

## Getting Started

How to install Crossbar.io, and start using it with your language or device of choice. 

* [Quick Start](Quick Start) - see #38 
* [The Command Line](The Command Line) - learn to use Crossbar.io with the Command Line
* [Application Templates](Application Templates) - play with demos to get into the code

**Comment by goeddea** [comment]
Current state is not ideal, but we want the intro doc page to be easily scannable. So closing for now - but this is an aspect we should think about when we next really shake things up regarding the docs.
