### ISSUE TITLE
Is it pusher or publisher ?

### ISSUE THREAD

**Issue by sametmax** [crossbario/crossbarwww#55]
Doc says the http bridge has type == "pusher" and my tuto too (and it used to work).

But greping the last code gives me:

    worker/router.py:        elif path_config['type'] == 'publisher':

Is that a compatibility breaking change ?

**Comment by goeddea** [comment]
Yes, it is. I just deployed the updated documentation. (Sorry, this was ready but hadn't been deployed).

The reason for the name change is that we're extending the HTTP bridge functionality. There's now a "publisher" and "caller", and we're working on the other roles. "Pusher" just doesn't fit with that naming scheme.

Sorry for breaking things, but I think this makes things more consistent down the road.

**Comment by sametmax** [comment]
Creating an alias would have been a better way of handling this (it breaks some demos as well) but since crossbar.io is not in version 1.0 yet, i guess it's fair game. Breaking things to make a clean slate is now or never.

**Comment by oberstet** [comment]
@sametmax yep, with 1.0 at last, we will need to handle such things much more strictly providing a dependable API / backward compat.
