### ISSUE TITLE
REST bridge docs: callee and subscriber

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbarwww#56]
@hawkowl Did I forget to merge this? Is there anything yet?

**Comment by hawkowl** [comment]
@oberstet I think I was waiting for feedback on the API which the examples use (https://github.com/crossbario/crossbarexamples/tree/master/rest) before I did anything major, and then it fell through the cracks :(

I'll flesh these out. :) I'm not sure about where to put them though -- the HTTP Bridge Services page seems like it has a lot of things on it, so it might be worth splitting it up into the different roles so it's less confusing for readers and easier to navigate. Thoughts?

**Comment by oberstet** [comment]
Ah, right;) Thanks!

Yes, splitting up into 5 pages would make sense: 1 overview on bridge services, then 1 page for each role.

**Comment by oberstet** [comment]
Popped up because of https://github.com/crossbario/crossbar/issues/309

**Comment by hawkowl** [comment]
Sounds good, I'll split it up and open a PR, and then make another PR off that which adds the new roles docs.

Does the website handle pages in folders? Like, HTTP-Bridge-Services/index.md sort of thing?

**Comment by oberstet** [comment]
No, it doesn't handle folders. You could name pages like HTTP-Bridge-Services.md, HTTP-Bridge-Services-Caller.md, ...

**Comment by hawkowl** [comment]
That works too, I'll do it like that :)

**Comment by oberstet** [comment]
The REST bridge is fine as is .. we just need docs;)

**Comment by hawkowl** [comment]
Here's the first PR, which just does the splitting work. I'll base the new docs off that.

**Comment by hawkowl** [comment]
These have been added :)
