### ISSUE TITLE
http://crossbar.io/docs/Invokation-Rules/ page missing in sources

### ISSUE THREAD

**Issue by rutsky** [crossbario/crossbarwww#64]
Looks like corresponding Markdown file should be in website/crossbario/docs/ directory of the repository, but it isn't.

P.S. There is a typo in "invokation" spelling across whole site, but I can't propose pull request to fix it, because not all site content in the git repository.

**Comment by oberstet** [comment]
@goeddea did we loose a page somewhere?

**Comment by goeddea** [comment]
We didn't lose a page. The page title was changed to 'Shared Registrations'. There is no deletion of legacy pages during our deployment (just overwriting of existing ones), so the old page 'Invokation Rules' still existed. This was still linked from one other page.

Fixed the link and the remaining misspellings of "invocation". 
Also deleted the legacy page on S3. 

@rutsky - Thanks for pointing this out!

**Comment by rutsky** [comment]
@goeddea there is still links on "Invokation Rules" page in website/crossbario/docs/WAMP-Features.md and website/crossbario/docs/How-Registrations-Work.md, which are now broken.

**Comment by goeddea** [comment]
Thanks once more! Mea culpa - that has hopefully taught me to watch case-sensitivity when searching for a term. 
Fixed and deployed.
