### ISSUE TITLE
Bad demo instance address

### ISSUE THREAD

**Issue by Vayel** [crossbario/crossbarwww#66]
[Here](https://github.com/crossbario/crossbarwww/blob/master/website/crossbario/docs/Demo-Instance.md). 

Maybe due to "under construction" and to be updated later?

**Comment by goeddea** [comment]
Yes - will be updated once we've updated the demo instance to current crossbar.

**Comment by goeddea** [comment]
Fixed this with commit f9d03aa6cf793755f8c99bfbe16211b8bda69805 (only forgot to mention in the commit message).
