### ISSUE TITLE
Arduino Yun post needs more love

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbarwww#73]
Users have questions on this popular post (this page has 2k views per month).
There are issues with the tutorial, and we now have the IoT cookbook. We should point users to that.

In general, best would be: hooking up the Yun via AutobahnPython/asyncio (as this does away with a lot of Twisted related hassle) and using Crossbar.io.

http://tavendo.com/blog/post/arduino-yun-with-autobahn/

**Comment by oberstet** [comment]
@meejah @hawkowl do you have an Arduino Yun. Are you interested in IoT / devices?

**Comment by hawkowl** [comment]
I'm rather interested, but don't have a Yun.

**Comment by goeddea** [comment]
Added a link to the IoT Cookbook at the top of the blog post.

**Comment by goeddea** [comment]
Added a reference to the IoT cookbook to the blog post.

**Comment by goeddea** [comment]
The post points to the newer materials.

As we're no longer particularly interested in the Yun (esp. since there are no a lot of alternatives in the Linux SBC + Arduino space), I consider this no longer important.
